# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 11:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hommalinna_sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(blank='true', default=datetime.datetime.now)),
            ],
        ),
    ]
