# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-27 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hommalinna_sites', '0002_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='id',
        ),
        migrations.AlterField(
            model_name='location',
            name='token',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
